---
# =============================================================================
# Bootstrap Playbook — Install Python on Linux targets
# =============================================================================
# Run this ONCE before using site.yml. The 'raw' module works over SSH
# without needing Python on the remote host.
#
# Ansible 2.17+ requires Python 3.7+ on managed nodes. CentOS 7 ships with
# Python 3.6, so this script installs a compatible Python via SCL/AppStream.
#
# Usage:
#   ansible-playbook init.yml
# =============================================================================

- name: Bootstrap Python on Linux hosts
  hosts: linux
  gather_facts: false
  become: false

  vars_prompt:
    - name: ansible_password
      prompt: "Enter SSH password for Linux hosts"
      private: true

  tasks:
    # -------------------------------------------------------------------------
    # Step 1: Fix CentOS 7 & 8 EOL repos (both are end-of-life)
    # -------------------------------------------------------------------------
    - name: Fix CentOS 7/8 EOL repository URLs
      ansible.builtin.raw: |
        if [ -f /etc/centos-release ]; then
          if grep -q "release 7" /etc/centos-release 2>/dev/null; then
            sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*.repo
            sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo
            if [ -f /etc/yum.repos.d/epel.repo ]; then
              sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/epel.repo
              sed -i 's|^#*baseurl=http://download.fedoraproject.org/pub/epel/|baseurl=https://archives.fedoraproject.org/pub/archive/epel/|g' /etc/yum.repos.d/epel.repo
            fi
            yum clean all
            echo "CentOS 7 repos fixed to vault.centos.org"
          elif grep -q "release 8" /etc/centos-release 2>/dev/null; then
            sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*.repo
            sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo
            if [ -f /etc/yum.repos.d/epel.repo ]; then
              sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/epel.repo
              sed -i 's|^#*baseurl=http://download.fedoraproject.org/pub/epel/|baseurl=https://archives.fedoraproject.org/pub/archive/epel/|g' /etc/yum.repos.d/epel.repo
            fi
            dnf clean all
            echo "CentOS 8 repos fixed to vault.centos.org"
          fi
        else
          echo "Not CentOS, skipping repo fix"
        fi
      register: repo_fix
      changed_when: "'repos fixed' in repo_fix.stdout"

    # -------------------------------------------------------------------------
    # Step 2: Install a compatible Python (3.8+)
    # -------------------------------------------------------------------------

    # CentOS 7: Python 3.8 via SCL
    - name: Install Python 3.8 via SCL on CentOS 7
      ansible.builtin.raw: |
        if [ -f /etc/centos-release ] && grep -q "release 7" /etc/centos-release 2>/dev/null; then
          if [ -f /opt/rh/rh-python38/root/usr/bin/python3.8 ]; then
            echo "Python 3.8 SCL is already installed"
          else
            yum install -y centos-release-scl-rh
            sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-SCL*.repo 2>/dev/null || true
            sed -i 's|^# *baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-SCL*.repo 2>/dev/null || true
            yum install -y rh-python38-python
            echo "Python 3.8 SCL installed"
          fi
          ln -sf /opt/rh/rh-python38/root/usr/bin/python3.8 /usr/local/bin/python3
          echo "Symlink created: /usr/local/bin/python3 -> python3.8"
        else
          echo "Not CentOS 7, skipping SCL"
        fi
      register: scl_install
      changed_when: "'SCL installed' in scl_install.stdout"

    # CentOS 8: Python 3.8 or 3.9 via AppStream
    - name: Install Python 3.8+ on CentOS 8
      ansible.builtin.raw: |
        if [ -f /etc/centos-release ] && grep -q "release 8" /etc/centos-release 2>/dev/null; then
          if /usr/local/bin/python3 --version 2>/dev/null | grep -qE "3\.([89]|[1-9][0-9])"; then
            echo "Python 3.8+ already available at /usr/local/bin/python3"
          else
            dnf install -y python39 || dnf install -y python38
            if [ -f /usr/bin/python3.9 ]; then
              ln -sf /usr/bin/python3.9 /usr/local/bin/python3
            elif [ -f /usr/bin/python3.8 ]; then
              ln -sf /usr/bin/python3.8 /usr/local/bin/python3
            fi
            echo "Python 3.8+ installed via AppStream"
          fi
        else
          echo "Not CentOS 8, skipping"
        fi
      register: centos8_python
      changed_when: "'installed via AppStream' in centos8_python.stdout"

    # Debian/Ubuntu
    - name: Install Python 3 via apt (Debian-based)
      ansible.builtin.raw: |
        if command -v python3 >/dev/null 2>&1; then
          echo "Python 3 is already installed"
        elif command -v apt-get >/dev/null 2>&1; then
          apt-get update -qq && apt-get install -y python3
        fi
      register: python_install_apt
      changed_when: "'already installed' not in python_install_apt.stdout"

    # -------------------------------------------------------------------------
    # Step 3: Verify
    # -------------------------------------------------------------------------
    - name: Verify Python installation
      ansible.builtin.raw: /usr/local/bin/python3 --version 2>/dev/null || python3 --version 2>/dev/null || python --version
      register: python_version

    - name: Show Python version
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: {{ python_version.stdout | trim }}"
