---
# =============================================================================
# SCAP Compliance Checker (SCC) Playbook
# =============================================================================
# Installs SCC from predefined installers and runs a local scan on all hosts.
#
# Usage:
#   ansible-playbook scc.yml
#
# Prerequisite:
#   Ensure the unzipped SCC installers are placed in the "files/" directory 
#   before running the playbook. The expected paths are:
#   - files/scc-5.14_ubuntu18_amd64/scc-5.14.ubuntu.18_amd64.deb (Debian/Ubuntu)
#   - files/scc-5.14_rhel7_x86_64/scc-5.14.rhel7.x86_64.rpm (RHEL/CentOS 7)
#   - files/scc-5.14_rhel8_x86_64/scc-5.14.rhel8.x86_64.rpm (RHEL/CentOS 8)
#   - files/scc-5.14_Windows/SCC_5.14_Windows_Setup.exe (Windows)
# =============================================================================

- name: Install and run SCAP Compliance Checker
  hosts: all
  gather_facts: true
  tasks:
    - name: Apply SCC role on Linux devices
      block:
        - ansible.builtin.include_role:
            name: scc
      when: ansible_os_family != 'Windows'

    - name: Apply SCC role on Windows devices
      ansible.builtin.include_role:
        name: scc
      when: ansible_os_family == 'Windows'
